version: "3"

services:
  db:
    image: taehoony/postgres_server:1.1
    container_name: postgres
    restart: always
    ports:
            - "55432:5432"
    environment:
            POSTGRES_USER: "keti_superuser"
            POSTGRES_PASSWORD: "madcoder"
    volumes:
            - /home/taehoon/Backup_Data/postgres_3dp_data:/var/lib/postgresql/data
