version: "3"

networks:
  3pdx-bridge:
    external: true

services:
  postgres-master:
    # 이미지는 최신이미지 사용하지 말기 ( 잘 안됨 )
    image: taehoony/postgres:1.3
    container_name: postgres_3pdx
    restart: always
    ports:
      - 54422:5432
    environment:
      POSTGRES_USER: "keti_root"
      POSTGRES_PASSWORD: "madcoder"
      POSTGRES_DB: "keti_3pdx"
    volumes:
      - /home/keti3dp/disks/disk0/data/postgres:/var/lib/postgresql/data
    networks:
      - 3pdx-bridge

  postgres-replica:
    # 이미지는 최신이미지 사용하지 말기 ( 잘 안됨 )
    image: taehoony/postgres:1.3
    container_name: postgres_3pdx_replica
    restart: always
    ports:
      - 54423:5432
    environment:
      POSTGRES_USER: "keti_root"
      POSTGRES_PASSWORD: "madcoder"
      POSTGRES_DB: "keti_3pdx"
      REPLICATE_FROM: postgres-master
    volumes:
      - /home/keti3dp/disks/disk1/data/postgres:/var/lib/postgresql/data
    networks:
      - 3pdx-bridge

  adminer:
    image: adminer:latest
    depends_on:
      - postgres-master
    restart: always
    ports:
      - 54424:8080
    networks:
      - 3pdx-bridge