version: "3"

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - 54422:5432
    environment:
      POSTGRES_USER: "keti_superuser"
      POSTGRES_PASSWORD: "madcoder"
      POSTGRES_DB: "NameOfDB"
    volumes:
      - /home/keti_data/Data/Postgres/data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    depends_on:
      - db
    restart: always
    ports:
      - 54423:8080
