version: "3"

services:
  db:
    # 이미지는 최신이미지 사용하지 말기 ( 잘 안됨 )
    image: taehoony/postgres_3pdx:1.2
    container_name: postgres
    restart: always
    ports:
      - 54422:5432
    environment:
      POSTGRES_USER: "keti_root"
      POSTGRES_PASSWORD: "madcoder"
      POSTGRES_DB: "BRAI"
    volumes:
      - /home/keti_data/Data/Postgres/data:/var/lib/postgresql/data
        #- /home/keti_data/Data/Postgres/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh

  adminer:
    image: adminer:latest
    depends_on:
      - db
    restart: always
    ports:
      - 54423:8080
