version: '3.1'

services:
  influxdb:
    image: influxdb:latest
    container_name: influx
    ports:
      - "58086:8086"
    environment:
      INFLUXDB_DB: mydb
      INFLUXDB_ADMIN_USER: keti_root
      INFLUXDB_ADMIN_PASSWORD: madcoder
    volumes:
      - influxdb-data:/var/lib/influxdb
    restart: always
    networks:
      - net3dp

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "53000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=keti_root
      - GF_SECURITY_ADMIN_PASSWORD=madcoder
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - net3dp
    restart: always

volumes:
  influxdb-data:
    driver: local
  grafana-data:
    driver: local

networks:
  net3dp:
    driver: bridge
