# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name : mongo_3pdx
    restart: always
    ports:
            - 27017:27017
    volumes:
            - /home/taehoon/Backup_Data/mongo_3dp_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: keti_root
      MONGO_INITDB_ROOT_PASSWORD: madcoder