version: '3'

networks:
  3pdx-bridge:
    external: true
    
services:

  minio:
    image: taehoony/minio:1.3
    command: server /data --console-address ":9001"
    container_name: minio
    environment:
      MINIO_ROOT_USER: keti_root
      MINIO_ROOT_PASSWORD: madcoder
    restart: always
    shm_size: '1gb'
    ports:
      - "59000:9000"
      - "59001:9001"
    volumes:
      - /home/keti3dp/Minio/data:/data
    networks:
      - 3pdx-bridge
