version: '3'

services:

  minio:
    image: taehoony/minio_server:1.1
    command: server /data --console-address ":9001"
    container_name: minio
    environment:
            MINIO_ROOT_USER: keti_root
            MINIO_ROOT_PASSWORD: madcoder
    restart: always
    shm_size: '1gb'
    ports:
            - "59000:9000"
            - "59001:9001"
    volumes:
            - /home/taehoon/Backup_Data/minIO_3dp_data:/data