# 파일 규격 버전
version: "3"

# 실행하려는 컨테이너들 정의
services: 
  # 서비스명
  redis:
    # 사용할 이미지
    image: redis:latest
    # 컨테이너명
    container_name: redis_3pdx
    hostname: redis
    # 접근 포트 설정(컨테이너 외부:컨테이너 내부)
    ports:
      - 56379:6379
    # 스토리지 마운트(볼륨) 설정
    volumes:
      - /home/taehoon/Backup_Data/redis_3dp_data:/data
      - /home/taehoon/docker_compose/redis/redis.conf:/usr/local/etc/redis/redis.conf
    # 컨테이너에 docker label을 이용해서 메타데이터 추가
    labels:
      - "name=redis"
      - "mode=standalone"
    # 컨테이너 종료시 재시작 여부 설정
    restart: always
    command: redis-server /usr/local/etc/redis/redis.conf
  # 레디스 모니터링 서비스
  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - 58001:8001
    volumes:
      - /home/taehoon/Backup_Data/redis_3dp_data:/db